# Generated by Django 5.1.2 on 2025-01-29 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Judet",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nume", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Adaugă Județ",
                "verbose_name_plural": "Adaugă Județe",
            },
        ),
        migrations.CreateModel(
            name="Localitate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("JUD_COD", models.CharField(max_length=40)),
                ("COD", models.CharField(max_length=40)),
                ("cod_POLITIE", models.CharField(max_length=24)),
                ("DENUMIRE", models.CharField(max_length=255)),
                ("TPL_COD", models.CharField(max_length=30)),
                ("COD_POSTAL", models.CharField(blank=True, max_length=20, null=True)),
                ("LOC_JUD_COD", models.CharField(max_length=40)),
                ("LOC_COD", models.CharField(max_length=40)),
                (
                    "judet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localitati",
                        to="adrese.judet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adaugă Localități",
                "verbose_name_plural": "Adaugă Localități",
            },
        ),
        migrations.CreateModel(
            name="CodPostal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("LOC_JUD_COD", models.CharField(max_length=40)),
                ("LOC_COD", models.CharField(max_length=40)),
                ("COD", models.BigIntegerField(blank=True, null=True)),
                ("BLOC", models.CharField(max_length=40)),
                ("COD_POSTAL", models.BigIntegerField(blank=True, null=True)),
                (
                    "localitate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coduri_postale",
                        to="adrese.localitate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelatiiLocalitati",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loc_jud_cod_nou", models.IntegerField()),
                ("loc_cod_nou", models.IntegerField()),
                (
                    "localitate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatii",
                        to="adrese.localitate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Strada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("LOC_JUD_COD", models.CharField(max_length=40)),
                ("LOC_COD", models.CharField(max_length=10)),
                ("COD", models.CharField(max_length=40)),
                ("COD_POLITIE", models.IntegerField()),
                ("DENUMIRE", models.CharField(max_length=40)),
                ("TAT_COD", models.CharField(max_length=40)),
                ("COD_POSTAL", models.CharField(max_length=40)),
                (
                    "localitate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strazi",
                        to="adrese.localitate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adaugă Strada",
                "verbose_name_plural": "Adaugă Strazi",
            },
        ),
    ]
