# Generated by Django 5.2.4 on 2025-09-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Serviciu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titlu", models.CharField(max_length=100, verbose_name="Titlu")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("termice", "Centrale Termice"),
                            ("clima", "Aer Condiționat"),
                        ],
                        max_length=10,
                        verbose_name="Categorie",
                    ),
                ),
                ("continut_html", models.TextField(verbose_name="Conținut")),
                ("activ", models.BooleanField(default=True, verbose_name="Activ")),
            ],
        ),
    ]
