# Generated by Django 5.2.4 on 2025-09-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servicii", "002_mig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviciu",
            name="continut_html",
        ),
    ]
