# Generated by Django 5.2.4 on 2025-09-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicii", "0003_remove_serviciu_continut_html"),
    ]

    operations = [
        migrations.CreateModel(
            name="PretServiciu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "denumire",
                    models.CharField(max_length=200, verbose_name="Denumire serviciu"),
                ),
                (
                    "pret",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preț (lei)"
                    ),
                ),
                (
                    "serviciu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preturi",
                        to="servicii.serviciu",
                        verbose_name="Serviciu",
                    ),
                ),
            ],
        ),
    ]
