# Generated by Django 5.2.4 on 2025-10-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicii", "0004_pretserviciu"),
    ]

    operations = [
        migrations.AddField(
            model_name="pretserviciu",
            name="categorie",
            field=models.CharField(
                choices=[("standard", "Standard"), ("suplimentar", "Suplimentar")],
                default="standard",
                max_length=20,
                verbose_name="Categorie preț",
            ),
        ),
    ]
