# Generated by Django 5.2.4 on 2025-10-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicii", "0005_pretserviciu_categorie"),
    ]

    operations = [
        migrations.AddField(
            model_name="pretserviciu",
            name="um",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Unitatea de măsură"
            ),
        ),
    ]
