# Generated by Django X.Y on 2025-09-13
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('servicii', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciu',
            name='continut_html',
            field=models.TextField(verbose_name='Conținut'),
        ),
    ]
