# Generated by Django 5.1.2 on 2025-01-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anexa3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titlu", models.CharField(max_length=255, verbose_name="Titlu")),
                (
                    "descriere",
                    models.TextField(blank=True, null=True, verbose_name="Descriere"),
                ),
                ("data_creare", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Anexa 3",
                "verbose_name_plural": "Anexe 3",
            },
        ),
    ]
