# Generated by Django 5.1.2 on 2025-01-30 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adrese", "0001_initial"),
        ("raportare", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rezolvat",
                    models.BooleanField(default=False, verbose_name="REZOLVAT"),
                ),
                (
                    "nr_solicit",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("data_solicit", models.DateTimeField(auto_now_add=True)),
                (
                    "judet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="adrese.judet",
                    ),
                ),
                (
                    "localitate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="adrese.localitate",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "strada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="adrese.strada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitare",
                "verbose_name_plural": "Solicitări",
            },
        ),
    ]
