# Generated by Django 5.1.2 on 2025-01-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("raportare", "0002_solicitari"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solicitari",
            options={"verbose_name": "Solicitar", "verbose_name_plural": "Solicităr"},
        ),
    ]
