# Generated by Django 5.1.5 on 2025-01-30 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("raportare", "0003_alter_solicitari_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Solicitari",
        ),
    ]
