# Generated by Django 5.1.5 on 2025-02-21 19:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiari", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(db_index=True, max_length=255)),
                ("prenume", models.CharField(max_length=255)),
                ("telefon", models.CharField(db_index=True, max_length=15)),
                (
                    "tip_client",
                    models.CharField(
                        choices=[
                            ("fizic", "Persoana Fizică"),
                            ("juridic", "Persoana Juridică"),
                        ],
                        max_length=20,
                        verbose_name="Tip Client",
                    ),
                ),
                (
                    "rezolvat",
                    models.BooleanField(default=False, verbose_name="REZOLVAT"),
                ),
                (
                    "nr_solicit",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="NUMĂR SOLICITARE",
                    ),
                ),
                (
                    "data_solicit",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="DataS"
                    ),
                ),
                (
                    "tip_interventie",
                    models.CharField(max_length=100, verbose_name="Tip intervenție"),
                ),
                (
                    "producator",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Producător Centrală",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Model Centrală",
                    ),
                ),
                (
                    "data_program",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data programării"
                    ),
                ),
                (
                    "ora_program",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Ora programării"
                    ),
                ),
                (
                    "observatii",
                    models.TextField(blank=True, null=True, verbose_name="Observații"),
                ),
                (
                    "beneficiar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="beneficiari.beneficiar",
                        verbose_name="Beneficiar",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitari_operator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OPERATOR INTERVENȚIE",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitare",
                "verbose_name_plural": "Solicitări",
                "ordering": ["-data_solicit"],
            },
        ),
    ]
