# Generated by Django 5.1.5 on 2025-01-31 21:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adrese", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rezolvat",
                    models.BooleanField(default=False, verbose_name="REZOLVAT"),
                ),
                (
                    "nr_solicit",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="NUMĂR SOLICITARE",
                    ),
                ),
                (
                    "data_solicit",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="DataS"
                    ),
                ),
                (
                    "nume",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nume Beneficiar",
                    ),
                ),
                (
                    "prenume",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Prenume"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "nr",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Număr"
                    ),
                ),
                (
                    "bloc",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Bloc"
                    ),
                ),
                (
                    "sc",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Scară"
                    ),
                ),
                (
                    "ap",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Apartament"
                    ),
                ),
                (
                    "tip_interventie",
                    models.CharField(max_length=100, verbose_name="Tip intervenție"),
                ),
                (
                    "producator",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Producător Centrală",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Model Centrală",
                    ),
                ),
                ("data_program", models.DateField(verbose_name="Data programarii")),
                ("ora_program", models.TimeField(verbose_name="Ora programării")),
                (
                    "observatii",
                    models.TextField(blank=True, null=True, verbose_name="Observații"),
                ),
                (
                    "judet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitari_judet",
                        to="adrese.judet",
                        verbose_name="Județ",
                    ),
                ),
                (
                    "localitate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitari_localitate",
                        to="adrese.localitate",
                        verbose_name="Localitate",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitari_operator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="OPERATOR INTERVENȚIE",
                    ),
                ),
                (
                    "strada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitari_strada",
                        to="adrese.strada",
                        verbose_name="Stradă",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitare",
                "verbose_name_plural": "Solicitări",
                "ordering": ["-data_solicit"],
            },
        ),
    ]
