# Generated by Django 5.1.5 on 2025-02-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitari", "0002_solicitari_bloc_solicitari_cod_postal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitari",
            name="etaj",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="solicitari",
            name="scara",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
