"""
Django settings for goGAS project.

Generated by 'django-admin startproject' using Django 5.1.2.
"""

from pathlib import Path
import sys
import os
from datetime import timedelta

# 📌 Construim calea de bază a proiectului
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.append(os.path.join(BASE_DIR, "venv", "Lib"))

# 📌 Securitate
SECRET_KEY = "django-insecure-b_37lczy0e_*i*0nyw1j9oss3*h0ol#gs(=-2dw2*r=6(&zfsb"
DEBUG = True

# 📌 Permitem accesul din rețea locală
ALLOWED_HOSTS = ["localhost", "172.16.0.105", "*"]

# 📌 Aplicațiile instalate
INSTALLED_APPS = [
    "admin_interface",  # Trebuie să fie PRIMA aplicație custom
    "colorfield",  # Necesită această dependență
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "solicitari",
    "adrese",
    "beneficiari",
    "raportare",
    "axios",
    "rest_framework",  # Django REST Framework
    "rest_framework_simplejwt",  # JWT Authentication
    "dal",
    "dal_select2",
]

# 📌 Middleware-uri Django
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# 📌 Configurare URL principal
ROOT_URLCONF = "goGAS.urls"
LOGIN_REDIRECT_URL = (
    "/admin/dashboard/"  # Utilizatorii autentificați sunt trimiși la dashboard
)

# 📌 Configurare Templates
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Asigură-te că această linie există
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# 📌 Configurare WSGI
WSGI_APPLICATION = "goGAS.wsgi.application"

# 📌 Configurare baza de date (folosește variabile de mediu pentru parola)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",  # Motorul bazei de date
        "NAME": "stargas",  # Numele bazei de date
        "USER": "root",  # Numele utilizatorului de MySQL
        "PASSWORD": os.getenv(
            "DJANGO_DB_PASSWORD", "egoqwedc/12"
        ),  # Folosește variabilă de mediu
        "HOST": "localhost",  # Adresa hostului, de obicei 'localhost'
        "PORT": "3306",  # Portul MySQL, implicit 3306
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# 📌 Validatori pentru parole
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# 📌 Configurare limbă și fus orar
LANGUAGES = [
    ("ro", "Română"),
    ("en", "English"),
]
TIME_ZONE = "Europe/Bucharest"
USE_I18N = True
USE_TZ = True

# 📌 Configurare fișiere statice
STATIC_URL = "/static/"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATICFILES_DIRS = [BASE_DIR / "static"]  # Asigură-te că `static/` există
STATIC_ROOT = BASE_DIR / "staticfiles"
# Servește fișierele statice mai rapid
INSTALLED_APPS += ["whitenoise.runserver_nostatic"]
MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

# 📌 Configurare fișiere media
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# 📌 Configurare Django REST Framework și autentificare JWT
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",  # API-ul necesită autentificare
    ),
}

# 📌 Configurare JSON Web Token (JWT)
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),  # 🔹 Tokenul de acces expiră în 1 oră
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=7
    ),  # 🔹 Refresh token-ul este valid 7 zile
    "ROTATE_REFRESH_TOKENS": True,
}

# 📌 Redirecționare după login (ex: la Admin solicitari)
LOGIN_REDIRECT_URL = "/admin/solicitari/"

# 📌 Tip implicit pentru cheile primare
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"