# Generated by Django 5.2.4 on 2025-07-31 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adrese", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(db_index=True, max_length=255)),
                ("prenume", models.CharField(db_index=True, max_length=255)),
                ("telefon", models.CharField(db_index=True, max_length=15)),
                ("nr", models.CharField(blank=True, max_length=10, null=True)),
                ("bloc", models.CharField(blank=True, max_length=10, null=True)),
                ("cod_postal", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "tip_client",
                    models.CharField(
                        choices=[
                            ("fizic", "Persoana Fizică"),
                            ("juridic", "Persoana Juridică"),
                        ],
                        max_length=20,
                        verbose_name="Tip Client",
                    ),
                ),
                (
                    "judet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="adrese.judet",
                    ),
                ),
                (
                    "localitate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="adrese.localitate",
                    ),
                ),
                (
                    "strada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="adrese.artera",
                    ),
                ),
            ],
            options={
                "ordering": ["nume", "prenume"],
            },
        ),
    ]
