# Generated by Django 5.1.5 on 2025-02-25 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adrese", "0001_initial"),
        ("beneficiari", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiar",
            name="bloc",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="beneficiar",
            name="cod_postal",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="beneficiar",
            name="judet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="adrese.judet",
            ),
        ),
        migrations.AddField(
            model_name="beneficiar",
            name="localitate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="adrese.localitate",
            ),
        ),
        migrations.AddField(
            model_name="beneficiar",
            name="nr",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="beneficiar",
            name="strada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="adrese.artera",
            ),
        ),
    ]
