# Generated by Django 5.1.5 on 2025-02-03 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiari", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="beneficiar",
            options={"ordering": ["nume", "prenume"]},
        ),
    ]
